CONSTRUCT {
  # Submodel Element Collection (SMC)
  ?SMC_iri a aas:SubmodelElementCollection ;
    aassem:semanticId [
      a aas:Reference ;
      aasref:keys [
        a aas:Key ;
        aaskey:idType aaskeyt:Iri ;
        aaskey:value ?Property ;
      ] ;
    ] ;
    prov:wasDerivedFrom ?PropertyShape ;
    mas4ai:constructedByQuery "construct_smc_cardinality.rq" ;
  .
}
WHERE {
  {
    ?PropertyShape a sh:PropertyShape ;
      sh:maxCount ?maxCount ;
    .
    FILTER( ?maxCount > 1 )
  } UNION {
    ?PropertyShape a sh:PropertyShape .
    FILTER NOT EXISTS { ?PropertyShape sh:maxCount [] }
  }
  FILTER NOT EXISTS { ?PropertyShape sh:class [] } #filter out reference (object) properties

  BIND(iri(concat( "http://mas4ai.eu/id/smc/template/", struuid() )) as ?SMC_iri)
}