CONSTRUCT {
  # Property
  ?Property_iri a aas:MultiLanguageProperty ;
    aassem:semanticId [
      a aas:Reference ;
      aasref:keys [
        a aas:Key ;
        aaskey:idType aaskeyt:IRI ;
        aaskey:value ?Property ;
      ] ;
    ] ;
    prov:wasDerivedFrom ?PropertyShape ;
    mas4ai:constructedByQuery "construct_multi-lang-property.rq" ;
  .
}
WHERE {
  ?PropertyShape a sh:PropertyShape ;
    sh:path ?Property ;
    sh:datatype rdf:langString ;
  .

  BIND(iri(concat( "http://mas4ai.eu/id/property/template/", struuid() )) as ?Property_iri)
}