PREFIX prov:        <http://www.w3.org/ns/prov#>
PREFIX skos:        <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:         <http://www.w3.org/2001/XMLSchema#>
PREFIX mas4ai:      <http://example.org/MAS4AI_GenericModel#>
PREFIX aas:         <https://admin-shell.io/aas/3/0/RC02/>
PREFIX aasaas:      <https://admin-shell.io/aas/3/0/RC02/AssetAdministrationShell/>
PREFIX aasenv:      <https://admin-shell.io/aas/3/0/RC02/AssetAdministrationShellEnvironment/>
PREFIX aasdata:     <https://admin-shell.io/aas/3/0/RC02/HasDataSpecification/>
PREFIX aasdt:       <https://admin-shell.io/aas/3/0/RC02/DataTypeDefXsd/>
PREFIX aasida:      <https://admin-shell.io/aas/3/0/RC02/Identifiable/>
PREFIX aaside:      <https://admin-shell.io/aas/3/0/RC02/Identifier/>
PREFIX aaskey:      <https://admin-shell.io/aas/3/0/RC02/Key/>
PREFIX aaskeyt:     <https://admin-shell.io/aas/3/0/RC02/KeyTypes/>
PREFIX aaskind:     <https://admin-shell.io/aas/3/0/RC02/HasKind/>
PREFIX aaslprop:    <https://admin-shell.io/aas/3/0/RC02/MultiLanguageProperty/>
PREFIX aasmod:      <https://admin-shell.io/aas/3/0/RC02/ModelingKind/>
PREFIX aasprop:     <https://admin-shell.io/aas/3/0/RC02/Property/>
PREFIX aasrange:    <https://admin-shell.io/aas/3/0/RC02/Range/>
PREFIX aasref:      <https://admin-shell.io/aas/3/0/RC02/Reference/>
PREFIX aasreft:     <https://admin-shell.io/aas/3/0/RC02/ReferenceTypes/>
PREFIX aasrefe:     <https://admin-shell.io/aas/3/0/RC02/ReferenceElement/>
PREFIX aasrefer:    <https://admin-shell.io/aas/3/0/RC02/Referable/>
PREFIX aasrel:      <https://admin-shell.io/aas/3/0/RC02/RelationshipElement/>
PREFIX aassm:       <https://admin-shell.io/aas/3/0/RC02/Submodel/>
PREFIX aassmc:      <https://admin-shell.io/aas/3/0/RC02/SubmodelElementCollection/>
PREFIX aassem:      <https://admin-shell.io/aas/3/0/RC02/HasSemantics/>
PREFIX assetinf:    <https://admin-shell.io/aas/3/0/RC02/AssetInformation/>
PREFIX assetkind:   <https://admin-shell.io/aas/3/0/RC02/AssetKind/>